### ISSUE TITLE
JavaScript/TypeScript client

### ISSUE THREAD

**Issue by thanhnguyen2187** [proofrock/ws4sqlite#37]
Hi!

Many thanks for the awesome tool!

I'm planning to use it in my web application written in Svelte/TypeScript. Unfortunately, there is no JavaScript/TypeScript client yet. Are you planning to do it soon?

Regards.

**Comment by proofrock** [comment]
Hi Thanh, thanks!

To tell the truth, it's not on my immediate to-do list. I am not an expert of the ts/js ecosystem and I don't know (yet) how to "cook" an NPM library... but the real reason is that it's easy enough to use, at least from javascript, and a client wouldn't add much to the "vanilla" usage.

Basically, you compose a js object with the request, then call `fetch()` to send the request to the server - remember to add `Content-Type: application/json` - and parse the response object. If you need some code let me know.

Also, you may want to take a look to [sqliterg](https://github.com/proofrock/), that's something like a "successor" to ws4sqlite. The request and response is the same, and the configuration is a bit better IMHO.

Thanks again, let me know!

--G.

**Comment by thanhnguyen2187** [comment]
Many thanks for the detailed response! I guess I'll try the vanilla usage within my application first, and publish it as a library later if I can find the time to do so.

**Comment by proofrock** [comment]
My pleasure! Let me know if you need anything!
