### ISSUE TITLE
Allow positional parameters

### ISSUE THREAD

**Issue by thanhnguyen2187** [proofrock/ws4sqlite#40]
For example, we have this query:

```sql
INSERT INTO table VALUES (?, ?, ?)
```

Binding values to those questions marks are not supported by `ws4sqlite` (#39).

I know the documentation wrote that:

> If the query needs to be parametrized, named parameters can be defined in the statement using SQLite (e.g. `:id` or `@id`), and the proper values for them must be specified here.

However, it is a syntax supported by [SQLite itself](https://www.sqlite.org/c3ref/bind_blob.html):

> In the SQL statement text input to [sqlite3_prepare_v2()](https://www.sqlite.org/c3ref/prepare.html) and its variants, literals may be replaced by a [parameter](https://www.sqlite.org/lang_expr.html#varparam) that matches one of following templates:
>
> ```
> ?
> ?NNN
> :VVV
> @VVV
> $VVV 
>```
>
>In the templates above, NNN represents an integer literal, and VVV represents an alphanumeric identifier. The values of these parameters (also called "host parameter names" or "SQL parameters") can be set using the sqlite3_bind_*() routines defined here.

**Comment by thanhnguyen2187** [comment]
More context on why I need this: I was wrapping Drizzle around `ws4sqlite`/`sqliterg`, and Drizzle seems to only support positional parameters, which makes the wrapper works with `sqliterg`, but not `ws4sqlite`.

What do you think, @proofrock? Is there any deeper technical issue on why it's hard to support this?

**Comment by proofrock** [comment]
Not hard to support, actually; it's just that ws4sqlite doesn't mean to support everything that sqlite does. I went with the map approach because... well, I guess I liked it more. Also, allowed for a more intuitive deduplication (if you have two parameters that are the same, you just pass one, without tinkering with indexes).

Do you have an use case, or a preference? Nothing against implementing it.
